# Generated by Django 2.1.3 on 2018-11-23 15:45
import os
import logging
from django.db import migrations, models
import django.utils.timezone

logger = logging.getLogger('django')


def create_github_application(apps, schema_editor):
    Application = apps.get_model('oauth2_provider', 'Application')
    if Application.objects.filter(name='Github').exists():
        return

    Application.objects.create(
        name='github',
        redirect_uris='http://localhost:8000',
        authorization_grant_type='authorization-code',
        client_type='public'
    )


def revert_github_application(apps, schema_editor):
    Application = apps.get_model('oauth2_provider', 'Application')
    Application.objects.filter(name='Github').delete()


def create_django_admin_user(apps, schema_editor):
    try:
        from ..models import User
        User.objects.create_superuser(
            username=os.environ['DJANGO_ADMIN_USER'],
            password=os.environ['DJANGO_ADMIN_USER_PASSWORD'],
            email='root@root.com',
        )
    except KeyError:
        logger.warning('Could not create admin user - please check environment variables')


def revert_django_admin_user(apps, schema_editor):
    try:
        from ..models import User
        User.objects.get(username=os.environ['DJANGO_ADMIN_USER'])
    except KeyError:
        logger.warning('Could not delete admin user - please check environment variables')


def forwards_func(*args, **kwargs):
    create_github_application(*args, **kwargs)
    create_django_admin_user(*args, **kwargs)


def reverse_func(*args, **kwargs):
    revert_github_application(*args, **kwargs)
    revert_django_admin_user(*args, **kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
