# Generated by Django 2.1.3 on 2018-12-11 15:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0003_auto_20181205_1035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('private', models.BooleanField()),
                ('fork', models.BooleanField()),
                ('size', models.PositiveIntegerField()),
                ('stargazers_count', models.PositiveIntegerField()),
                ('forks', models.PositiveIntegerField()),
                ('watchers', models.PositiveIntegerField()),
                ('html_url', models.URLField()),
                ('ssh_url', models.URLField()),
                ('git_url', models.URLField()),
                ('raw_api_response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('github_id', models.PositiveIntegerField()),
                ('api_url', models.URLField()),
                ('license', models.CharField(max_length=256, null=True)),
                ('readme', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('pypi_name', models.CharField(blank=True, max_length=256, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repositories.Repository')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
