# Generated by Django 2.1.3 on 2018-12-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_auto_20181211_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='repo',
            new_name='repository',
        ),
    ]
