# Generated by Django 2.1.3 on 2018-12-19 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_auto_20181213_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environment',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=4),
        ),
    ]
