# Generated by Django 2.1.3 on 2018-12-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0006_auto_20181219_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='gym',
        ),
    ]
