# Generated by Django 2.1.7 on 2019-02-19 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0007_remove_environment_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('parent_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.Topic')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
