# Generated by Django 2.1.7 on 2019-03-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('environments', '0009_auto_20190219_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
    ]
