# Generated by Django 2.1.7 on 2019-03-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_hash'),
        ('environments', '0010_environment_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='avatar',
        ),
        migrations.AddField(
            model_name='environment',
            name='avatar',
            field=models.ManyToManyField(to='images.Image'),
        ),
    ]
