# Generated by Django 2.1.7 on 2019-03-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0011_auto_20190307_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='avatar',
            new_name='avatars',
        ),
    ]
