# Generated by Django 2.1.7 on 2019-03-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_image_description'),
        ('environments', '0012_auto_20190308_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='avatars',
        ),
        migrations.AddField(
            model_name='environment',
            name='current_avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
    ]
