# Generated by Django 2.1.7 on 2019-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0014_environment_scigym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
