# Generated by Django 2.1.7 on 2019-09-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0015_auto_20190512_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='url',
            field=models.CharField(default='default-not-unique', max_length=768, unique=True),
            preserve_default=False,
        ),
    ]
