# Generated by Django 2.1.7 on 2019-09-26 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0016_environment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-+]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='environment',
            name='url',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
