# Generated by Django 2.1.3 on 2018-12-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_auto_20181205_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='gym',
            field=models.BooleanField(default=False),
        ),
    ]
