# Generated by Django 2.1.3 on 2018-11-24 20:05

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('private', models.BooleanField()),
                ('fork', models.BooleanField()),
                ('size', models.PositiveIntegerField()),
                ('stargazers_count', models.PositiveIntegerField()),
                ('forks', models.PositiveIntegerField()),
                ('watchers', models.PositiveIntegerField()),
                ('html_url', models.URLField()),
                ('ssh_url', models.URLField()),
                ('git_url', models.URLField()),
                ('raw_api_response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('github_id', models.PositiveIntegerField()),
                ('api_url', models.URLField()),
                ('license', models.CharField(max_length=256, null=True)),
                ('readme', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='environment',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='fork',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='forks',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='git_url',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='github_id',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='html_url',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='license',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='private',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='raw_api_response',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='readme',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='size',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='ssh_url',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='stargazers_count',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='watchers',
        ),
        migrations.AddField(
            model_name='environment',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='environments.Repository'),
        ),
    ]
