# Generated by Django 2.1.3 on 2018-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_auto_20181123_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='license',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
