# Generated by Django 2.1.7 on 2019-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_auto_20190116_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='readme_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
