# Generated by Django 2.1.7 on 2019-09-26 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20190926_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-!?.,$ ]*$', 'Only alphanumeric characters and !?$-,. are allowed')]),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='title_url',
            field=models.CharField(max_length=350, unique=True),
        ),
    ]
