# Generated by Django 2.1.7 on 2019-03-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
