# Generated by Django 2.1.7 on 2019-06-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20190310_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload_path',
            field=models.TextField(default='/test'),
            preserve_default=False,
        ),
    ]
