# Generated by Django 2.1.7 on 2019-03-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ('-contributions',)},
        ),
        migrations.AddField(
            model_name='contributor',
            name='contributions',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
